export const ALL_CAUSES = [
  {
    slug: 'education-for-all',
    id: 1,
    title: 'Education for All',
    category: 'Education',
    icon: 'BookOpen',
    gradient: 'from-blue-500 to-indigo-600',
    textColor: 'text-blue-500',
    description: 'Providing quality education to 12,000+ underprivileged children in remote villages across Rajasthan and Bihar.',
    longDesc: 'Our education programme builds schools, trains teachers, provides digital learning tools, and offers scholarships so no child misses out due to poverty.',
    raised: 128500,
    goal: 200000,
    supporters: 1847,
    updates: 24,
    impact: ['12,400 children enrolled', '145 schools built', '380 teachers trained', '8,000 scholarships given'],
    endDate: 'Dec 2025',
    urgency: 'high',
  },
  {
    slug: 'clean-water-access',
    id: 2,
    title: 'Clean Water Access',
    category: 'Environment',
    icon: 'Droplets',
    gradient: 'from-cyan-500 to-teal-600',
    textColor: 'text-cyan-500',
    description: 'Installing bore wells and water purification systems in 80+ drought-prone villages in Maharashtra and Madhya Pradesh.',
    longDesc: 'Access to clean water reduces waterborne diseases by 80%. We build infrastructure that lasts decades and train local communities to maintain it.',
    raised: 89200,
    goal: 150000,
    supporters: 1203,
    updates: 18,
    impact: ['82 villages covered', '47,000 people served', '92% disease reduction', '200 wells installed'],
    endDate: 'Mar 2025',
    urgency: 'medium',
  },
  {
    slug: 'medical-relief-fund',
    id: 3,
    title: 'Medical Relief Fund',
    category: 'Healthcare',
    icon: 'HeartPulse',
    gradient: 'from-rose-500 to-pink-600',
    textColor: 'text-rose-500',
    description: 'Supplying medicines, medical equipment, and funding mobile health camps for rural communities with no healthcare access.',
    longDesc: 'Our mobile health camps reach 500+ villages monthly, providing free consultations, medicines, and emergency care to those who cannot afford doctors.',
    raised: 203800,
    goal: 300000,
    supporters: 3241,
    updates: 36,
    impact: ['500+ villages reached', '2.1L patients treated', '12 mobile clinics', '45 doctors volunteering'],
    endDate: 'Jun 2025',
    urgency: 'critical',
  },
  {
    slug: 'food-security-drive',
    id: 4,
    title: 'Food Security Drive',
    category: 'Food',
    icon: 'Utensils',
    gradient: 'from-amber-500 to-orange-600',
    textColor: 'text-amber-500',
    description: 'Providing nutritious meals to malnourished children and food-insecure families in urban slums and conflict zones.',
    longDesc: 'Our daily meal programme ensures 50,000 children receive nutritious food every day. We also run skill training for parents to achieve long-term food security.',
    raised: 72400,
    goal: 120000,
    supporters: 982,
    updates: 12,
    impact: ['50,000 meals/day', '320 feeding centres', '8,500 families supported', '45% malnutrition reduction'],
    endDate: 'Sep 2025',
    urgency: 'high',
  },
  {
    slug: 'disaster-relief-response',
    id: 5,
    title: 'Disaster Relief Response',
    category: 'Emergency',
    icon: 'AlertTriangle',
    gradient: 'from-red-500 to-rose-600',
    textColor: 'text-red-500',
    description: 'Emergency relief for flood, earthquake, and cyclone victims — shelter, food, medicines, and rehabilitation support.',
    longDesc: 'We deploy within 24 hours of a disaster. Our trained response teams provide immediate relief and stay for long-term rehabilitation and community rebuilding.',
    raised: 156900,
    goal: 250000,
    supporters: 4102,
    updates: 45,
    impact: ['8 disasters responded', '1.2L people helped', '24hr response time', '95 relief camps set up'],
    endDate: 'Ongoing',
    urgency: 'critical',
  },
  {
    slug: 'women-empowerment',
    id: 6,
    title: 'Women Empowerment',
    category: 'Social',
    icon: 'Users',
    gradient: 'from-purple-500 to-violet-600',
    textColor: 'text-purple-500',
    description: 'Skill training, microfinance, and legal support for rural women — helping them achieve financial independence and dignity.',
    longDesc: 'We run vocational training centres, provide zero-interest microloans, offer legal aid for domestic abuse survivors, and support women entrepreneurs.',
    raised: 44700,
    goal: 80000,
    supporters: 623,
    updates: 9,
    impact: ['6,200 women trained', '1,400 businesses started', '₹2.4Cr in microloans', '89% income increase'],
    endDate: 'Nov 2025',
    urgency: 'medium',
  },
]

export const CAUSES_SEED = ALL_CAUSES.map(({ slug, title, category, icon, description, longDesc, raised, goal, supporters, urgency, endDate }) => ({
  slug, title, category, icon, description, longDesc, raised, goal, supporters, urgency, endDate,
}))
